# Generated by Django 4.2 on 2024-08-06 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('cargaHoraria', models.IntegerField()),
                ('ementa', models.TextField()),
                ('bibliografia', models.TextField()),
                ('preRequisito', models.ManyToManyField(blank=True, to='disciplina.disciplina')),
            ],
        ),
        migrations.DeleteModel(
            name='cadastro',
        ),
    ]
